name = "trimmomatic"
version = "0.39.0"
channels = [
    "https://conda.anaconda.org/bioconda",
    "https://conda.anaconda.org/conda-forge",
]
packages = ["trimmomatic ==0.39"]
platform = "linux/amd64"

[entrypoint]
command = "/opt/conda/bin/trimmomatic"
