[tool]
id = "nanostat"
version = "1.6.0"
description = "Statistical summary and quality control for long-read Oxford Nanopore data"
homepage = "https://github.com/wdecoster/NanoStat"
license = "MIT"
tier = "community"
maintainers = [ "github:wdecoster",]
[[tool.inputs]]
name = "reads"
type = "fastq"
cardinality = "one"
description = "Nanopore FASTQ reads"

[[tool.outputs]]
name = "report"
type = "file"
cardinality = "one"
description = "Summary statistics in text format"

[tool.image]
backend = "docker"
reference = "quay.io/biocontainers/nanostat:1.6.0--pyhdfd78af_0"

[tool.hardware]
cpu_cores = 2
ram_gb = 4.0
disk_gb = 1.0

[tool.entrypoint]
command = "NanoStat"
args_template = "--threads {cpu_cores} --fastq {reads} > {report}"

[tool.binaries]
exposed = [ "NanoStat",]

[tool.factored]
spec_path = "specs/nanostat/1.6.0.yaml"
image_reference = "ghcr.io/tejasprabhune/bv-pkg/nanostat:1.6.0"
image_digest = "sha256:22982bd8f7b205b422b22e9c738e0ee84df551c2f077e90a32d1965101d8c5b4"
