[tool]
id = "seqtk"
version = "1.4.0"
description = "Fast toolkit for processing FASTA/FASTQ sequences: subsampling, conversion, trimming"
homepage = "https://github.com/lh3/seqtk"
license = "MIT"
tier = "community"
maintainers = [ "github:lh3",]
[[tool.inputs]]
name = "input"
type = "fastq"
cardinality = "one"
description = "Input FASTQ or FASTA file"

[[tool.outputs]]
name = "output"
type = "fastq"
cardinality = "one"
description = "Processed sequences"

[tool.image]
backend = "docker"
reference = "quay.io/biocontainers/seqtk:1.4--he4a0461_1"

[tool.hardware]
cpu_cores = 1
ram_gb = 2.0
disk_gb = 1.0

[tool.entrypoint]
command = "seqtk"
args_template = "sample {input} 1000000 > {output}"

[tool.binaries]
exposed = [ "seqtk",]

[tool.factored]
spec_path = "specs/seqtk/1.4.0.yaml"
image_reference = "ghcr.io/tejasprabhune/bv-pkg/seqtk:1.4.0"
image_digest = "sha256:d1f8ce5d49fa6792dcce5121f80943fcfbc85e6ddea82368cf5f26db9691a5dd"
