name = "hifiasm"
version = "0.19.8"
channels = [
    "https://conda.anaconda.org/bioconda",
    "https://conda.anaconda.org/conda-forge",
]
packages = ["hifiasm ==0.19.8"]
platform = "linux/amd64"

[entrypoint]
command = "/opt/conda/bin/hifiasm"
