[tool]
id = "kallisto"
version = "0.51.1"
description = "Pseudo-alignment based RNA-seq transcript quantification"
homepage = "https://pachterlab.github.io/kallisto/"
license = "BSD-2-Clause"
tier = "core"
maintainers = [ "github:pachterlab",]
[[tool.inputs]]
name = "reads_r1"
type = "fastq"
cardinality = "one"
description = "Forward reads"

[[tool.inputs]]
name = "reads_r2"
type = "fastq"
cardinality = "optional"
description = "Reverse reads (paired-end)"

[[tool.outputs]]
name = "quant_dir"
type = "dir"
cardinality = "one"
description = "Quantification output with abundance.tsv"

[tool.image]
backend = "docker"
reference = "quay.io/biocontainers/kallisto:0.51.1--h2b92561_2"

[tool.hardware]
cpu_cores = 8
ram_gb = 8.0
disk_gb = 2.0

[tool.entrypoint]
command = "kallisto"
args_template = "quant --threads {cpu_cores} -i /workspace/index.idx -o {quant_dir} {reads_r1} {reads_r2}"

[tool.binaries]
exposed = [ "kallisto",]

[tool.factored]
spec_path = "specs/kallisto/0.51.1.yaml"
image_reference = "ghcr.io/tejasprabhune/bv-pkg/kallisto:0.51.1"
image_digest = "sha256:2e3776a8c7975394db2499c1c1b8864376f1e346268361bb0484195be4de76a7"
