name = "featurecounts"
version = "2.0.6"
channels = [
    "https://conda.anaconda.org/bioconda",
    "https://conda.anaconda.org/conda-forge",
]
packages = ["subread ==2.0.6"]
platform = "linux/amd64"

[entrypoint]
command = "/opt/conda/bin/featureCounts"
