[tool]
id = "hifiasm"
version = "0.19.8"
description = "Haplotype-resolved assembler for PacBio HiFi reads"
homepage = "https://github.com/chhylp123/hifiasm"
license = "MIT"
tier = "community"
maintainers = [ "github:chhylp123",]
[[tool.inputs]]
name = "reads"
type = "fastq"
cardinality = "one"
description = "PacBio HiFi reads"

[[tool.outputs]]
name = "output_prefix"
type = "file"
cardinality = "one"
description = "Output prefix for haplotype GFA/FASTA files"

[tool.image]
backend = "docker"
reference = "quay.io/biocontainers/hifiasm:0.19.8--h43eeafb_0"

[tool.hardware]
cpu_cores = 32
ram_gb = 64.0
disk_gb = 100.0

[tool.entrypoint]
command = "hifiasm"
args_template = "-o {output_prefix} -t {cpu_cores} {reads}"

[tool.binaries]
exposed = [ "hifiasm",]

[tool.factored]
spec_path = "specs/hifiasm/0.19.8.yaml"
image_reference = "ghcr.io/tejasprabhune/bv-pkg/hifiasm:0.19.8"
image_digest = "sha256:e51557765f3e6eee72d27bb49243228bbdeb84bfe66d61652209b96ada57db41"
