[tool]
id = "star"
version = "2.7.11"
description = "Spliced Transcripts Alignment to a Reference: RNA-seq aligner with splice junction detection"
homepage = "https://github.com/alexdobin/STAR"
license = "MIT"
tier = "core"
maintainers = [ "github:alexdobin",]
[[tool.inputs]]
name = "reads_r1"
type = "fastq"
cardinality = "one"
description = "Read 1 FASTQ file"

[[tool.inputs]]
name = "reads_r2"
type = "fastq"
cardinality = "optional"
description = "Read 2 FASTQ file (paired-end)"

[[tool.outputs]]
name = "bam"
type = "bam"
cardinality = "one"
description = "Aligned reads in BAM format"

[tool.image]
backend = "docker"
reference = "quay.io/biocontainers/star:2.7.11b--h43eeafb_0"

[tool.hardware]
cpu_cores = 8
ram_gb = 32.0
disk_gb = 30.0

[tool.entrypoint]
command = "STAR"
args_template = "--runThreadN {cpu_cores} --genomeDir /workspace/genome --readFilesIn {reads_r1} {reads_r2} --outSAMtype BAM SortedByCoordinate --outFileNamePrefix /workspace/star_"

[tool.binaries]
exposed = [ "STAR", "STARlong",]

[tool.factored]
spec_path = "specs/star/2.7.11.yaml"
image_reference = "ghcr.io/tejasprabhune/bv-pkg/star:2.7.11"
image_digest = "sha256:a7b3debea50661178961e8af403d1246ae5dc59fce184df15f1f5d1e139c0371"
