name = "bcftools"
version = "1.21.0"
channels = [
    "https://conda.anaconda.org/bioconda",
    "https://conda.anaconda.org/conda-forge",
]
packages = ["bcftools ==1.21"]
platform = "linux/amd64"

[entrypoint]
command = "/opt/conda/bin/bcftools"
