name = "samtools"
version = "1.21.0"
channels = [
    "https://conda.anaconda.org/bioconda",
    "https://conda.anaconda.org/conda-forge",
]
packages = ["samtools ==1.21"]
platform = "linux/amd64"

[entrypoint]
command = "/opt/conda/bin/samtools"
