name = "freebayes"
version = "1.3.7"
channels = [
    "https://conda.anaconda.org/bioconda",
    "https://conda.anaconda.org/conda-forge",
]
packages = ["freebayes ==1.3.7"]
platform = "linux/amd64"

[entrypoint]
command = "/opt/conda/bin/freebayes"
