name = "star"
version = "2.7.11"
channels = [
    "https://conda.anaconda.org/bioconda",
    "https://conda.anaconda.org/conda-forge",
]
packages = ["star ==2.7.11b"]
platform = "linux/amd64"

[entrypoint]
command = "/opt/conda/bin/STAR"
