[tool]
id = "muscle"
version = "5.1.0"
description = "MUSCLE: multiple sequence alignment with high accuracy and high throughput"
homepage = "https://www.drive5.com/muscle/"
license = "Public Domain"
tier = "community"
maintainers = [ "github:rcedgar",]
[[tool.inputs]]
name = "sequences"
type = "fasta"
cardinality = "one"
description = "Unaligned input sequences"

[[tool.outputs]]
name = "alignment"
type = "msa"
cardinality = "one"
description = "Multiple sequence alignment"

[tool.image]
backend = "docker"
reference = "quay.io/biocontainers/muscle:5.1--h9f5acd7_1"

[tool.hardware]
cpu_cores = 4
ram_gb = 4.0
disk_gb = 1.0

[tool.entrypoint]
command = "muscle"
args_template = "-align {sequences} -output {alignment} -threads {cpu_cores}"

[tool.binaries]
exposed = [ "muscle",]

[tool.factored]
spec_path = "specs/muscle/5.1.0.toml"
image_reference = "ghcr.io/tejasprabhune/bv-pkg/muscle:5.1.0"
image_digest = "sha256:971989606102c6241f26fe6996d6d29640d2165efb222a88594a666dfe453124"
