name = "fastqc"
version = "0.12.1"
channels = [
    "https://conda.anaconda.org/bioconda",
    "https://conda.anaconda.org/conda-forge",
]
packages = ["fastqc ==0.12.1"]
platform = "linux/amd64"

[entrypoint]
command = "/opt/conda/bin/fastqc"
