[tool]
id = "minimap2"
version = "2.28.0"
description = "Fast sequence alignment for long reads (PacBio, Oxford Nanopore) and spliced mRNA"
homepage = "https://github.com/lh3/minimap2"
license = "MIT"
tier = "core"
maintainers = [ "github:lh3",]
[[tool.inputs]]
name = "reads"
type = "fastq"
cardinality = "one"
description = "Query reads (FASTQ or FASTA)"

[[tool.inputs]]
name = "reference"
type = "fasta"
cardinality = "one"
description = "Reference sequence or assembly"

[[tool.outputs]]
name = "alignment"
type = "sam"
cardinality = "one"
description = "Alignment in SAM format"

[tool.image]
backend = "docker"
reference = "quay.io/biocontainers/minimap2:2.28--he4a0461_3"

[tool.hardware]
cpu_cores = 8
ram_gb = 16.0
disk_gb = 5.0

[tool.entrypoint]
command = "minimap2"
args_template = "-ax map-ont -t {cpu_cores} {reference} {reads} > {alignment}"

[tool.binaries]
exposed = [ "minimap2",]

[tool.factored]
spec_path = "specs/minimap2/2.28.0.yaml"
image_reference = "ghcr.io/tejasprabhune/bv-pkg/minimap2:2.28.0"
image_digest = "sha256:65d0533ed41e60e9d3460b55d41ddf7d73b507177d8681c93b13b92ba9aa0c1f"
