[tool]
id = "fastqc"
version = "0.12.1"
description = "Quality control analysis tool for high-throughput sequencing data"
homepage = "https://www.bioinformatics.babraham.ac.uk/projects/fastqc/"
license = "GPL-3.0"
tier = "core"
maintainers = [ "github:s-andrews",]
[[tool.inputs]]
name = "reads"
type = "fastq"
cardinality = "many"
description = "FASTQ files to assess"

[[tool.outputs]]
name = "report_dir"
type = "dir"
cardinality = "one"
description = "HTML and zip QC reports"

[tool.image]
backend = "docker"
reference = "quay.io/biocontainers/fastqc:0.12.1--hdfd78af_0"

[tool.hardware]
cpu_cores = 4
ram_gb = 4.0
disk_gb = 1.0

[tool.entrypoint]
command = "fastqc"
args_template = "--threads {cpu_cores} --outdir {report_dir} {reads}"

[tool.binaries]
exposed = [ "fastqc",]

[tool.factored]
spec_path = "specs/fastqc/0.12.1.yaml"
image_reference = "ghcr.io/tejasprabhune/bv-pkg/fastqc:0.12.1"
image_digest = "sha256:d0eca1f9200a2c299f1db9c774edc89644e6221574c129b9ab0b142b36ad0686"
