[tool]
id = "metaphlan4"
version = "4.1.1"
description = "MetaPhlAn 4: metagenomic profiling using marker genes from reference genomes"
homepage = "https://github.com/biobakery/MetaPhlAn"
license = "MIT"
tier = "community"
maintainers = [ "github:biobakery",]
[[tool.inputs]]
name = "reads"
type = "fastq"
cardinality = "one"
description = "Metagenomics reads"

[[tool.outputs]]
name = "profile"
type = "tabular"
cardinality = "one"
description = "Taxonomic abundance profile"

[tool.image]
backend = "docker"
reference = "quay.io/biocontainers/metaphlan:4.1.1--pyhdfd78af_0"

[tool.hardware]
cpu_cores = 8
ram_gb = 8.0
disk_gb = 10.0

[tool.entrypoint]
command = "metaphlan"
args_template = "{reads} --input_type fastq --nproc {cpu_cores} -o {profile}"

[tool.binaries]
exposed = [ "metaphlan", "merge_metaphlan_tables.py", "strainphlan",]

[tool.factored]
spec_path = "specs/metaphlan4/4.1.1.yaml"
image_reference = "ghcr.io/tejasprabhune/bv-pkg/metaphlan4:4.1.1"
image_digest = "sha256:8ff5f6217993b5651b6962002b9ec5731d1113d79b6021d9a9653f945b984b4f"
