[tool]
id = "prodigal"
version = "2.6.3"
description = "Prokaryotic gene recognition and translation initiation site identification"
homepage = "https://github.com/hyattpd/Prodigal"
license = "GPL-3.0"
tier = "core"
maintainers = [ "github:hyattpd",]
[[tool.inputs]]
name = "genome"
type = "fasta"
cardinality = "one"
description = "Input nucleotide sequence (genome or contigs)"

[[tool.outputs]]
name = "proteins"
type = "fasta[protein]"
cardinality = "one"
description = "Predicted protein sequences"

[[tool.outputs]]
name = "genes"
type = "file"
cardinality = "one"
description = "Gene predictions in GFF/GenBank format"

[tool.image]
backend = "docker"
reference = "quay.io/biocontainers/prodigal:2.6.3--h577a1d6_11"

[tool.hardware]
cpu_cores = 1
ram_gb = 2.0
disk_gb = 1.0

[tool.entrypoint]
command = "prodigal"
args_template = "-i {genome} -a {proteins} -f gff -o {genes}"

[tool.binaries]
exposed = [ "prodigal",]

[tool.factored]
spec_path = "specs/prodigal/2.6.3.yaml"
image_reference = "ghcr.io/tejasprabhune/bv-pkg/prodigal:2.6.3"
image_digest = "sha256:33d77a88c7ee0c21095fa3a991483d35b80245841c7a25a56528f096f38be14c"
