[tool]
id = "stringtie"
version = "2.2.3"
description = "Transcript assembly and quantification from RNA-seq alignments"
homepage = "https://ccb.jhu.edu/software/stringtie/"
license = "MIT"
tier = "core"
maintainers = [ "github:gpertea",]
[[tool.inputs]]
name = "bam"
type = "bam"
cardinality = "one"
description = "Sorted BAM alignment file"

[[tool.outputs]]
name = "gtf"
type = "file"
cardinality = "one"
description = "Assembled transcripts in GTF format with expression estimates"

[tool.image]
backend = "docker"
reference = "quay.io/biocontainers/stringtie:2.2.3--h29c0135_1"

[tool.hardware]
cpu_cores = 8
ram_gb = 8.0
disk_gb = 5.0

[tool.entrypoint]
command = "stringtie"
args_template = "-p {cpu_cores} -o {gtf} {bam}"

[tool.binaries]
exposed = [ "stringtie",]

[tool.factored]
spec_path = "specs/stringtie/2.2.3.toml"
image_reference = "ghcr.io/tejasprabhune/bv-pkg/stringtie:2.2.3"
image_digest = "sha256:2d908d701bd0fead51c40cd647e31d407ffc6256b2364814a0e5d80673496d3e"
