[tool]
id = "chopper"
version = "0.8.0"
description = "Quality filtering and trimming of Oxford Nanopore reads"
homepage = "https://github.com/wdecoster/chopper"
license = "MIT"
tier = "community"
maintainers = [ "github:wdecoster",]
[[tool.inputs]]
name = "reads"
type = "fastq"
cardinality = "one"
description = "Input Nanopore FASTQ reads"

[[tool.outputs]]
name = "output"
type = "fastq"
cardinality = "one"
description = "Quality-filtered reads"

[tool.image]
backend = "docker"
reference = "quay.io/biocontainers/chopper:0.8.0--hdcf5f25_0"

[tool.hardware]
cpu_cores = 4
ram_gb = 4.0
disk_gb = 1.0

[tool.entrypoint]
command = "sh"
args_template = "-c 'gunzip -c {reads} | chopper --threads {cpu_cores} --quality 8 --minlength 1000 | gzip > {output}'"

[tool.factored]
spec_path = "specs/chopper/0.8.0.yaml"
image_reference = "ghcr.io/tejasprabhune/bv-pkg/chopper:0.8.0"
image_digest = "sha256:e9490030e854bbde5214e59d124728d8d8c7dc0fbfd19d8a6ed5ce8624587f4c"
