[tool]
id = "bcftools"
version = "1.21.0"
description = "Utilities for variant calling and manipulating VCF/BCF files"
homepage = "http://www.htslib.org/doc/bcftools.html"
license = "MIT"
tier = "core"
maintainers = [ "github:samtools",]
[[tool.inputs]]
name = "input"
type = "vcf"
cardinality = "one"
description = "Input VCF or BCF file"

[[tool.outputs]]
name = "output"
type = "vcf"
cardinality = "one"
description = "Processed VCF or BCF file"

[tool.image]
backend = "docker"
reference = "quay.io/biocontainers/bcftools:1.21--h8b25389_0"

[tool.hardware]
cpu_cores = 4
ram_gb = 8.0
disk_gb = 2.0

[tool.entrypoint]
command = "bcftools"
args_template = "view --threads {cpu_cores} -o {output} {input}"

[tool.binaries]
exposed = [ "bcftools",]

[tool.factored]
spec_path = "specs/bcftools/1.21.0.yaml"
image_reference = "ghcr.io/tejasprabhune/bv-pkg/bcftools:1.21.0"
image_digest = "sha256:72d061a41a7a9afac1e306ea3a4a56ed4a791d72fbb4452844fed54d6f7db433"
