name = "kallisto"
version = "0.51.1"
channels = [
    "https://conda.anaconda.org/bioconda",
    "https://conda.anaconda.org/conda-forge",
]
packages = ["kallisto ==0.51.1"]
platform = "linux/amd64"

[entrypoint]
command = "/opt/conda/bin/kallisto"
