[tool]
id = "trimmomatic"
version = "0.39.0"
description = "Flexible read trimming tool for Illumina NGS data"
homepage = "http://www.usadellab.org/cms/?page=trimmomatic"
license = "GPL-3.0"
tier = "community"
maintainers = [ "github:usadellab",]
[[tool.inputs]]
name = "reads_r1"
type = "fastq"
cardinality = "one"
description = "Forward reads"

[[tool.inputs]]
name = "reads_r2"
type = "fastq"
cardinality = "optional"
description = "Reverse reads (paired-end)"

[[tool.outputs]]
name = "out_r1"
type = "fastq"
cardinality = "one"
description = "Trimmed paired forward reads"

[[tool.outputs]]
name = "out_r2"
type = "fastq"
cardinality = "optional"
description = "Trimmed paired reverse reads"

[tool.image]
backend = "docker"
reference = "quay.io/biocontainers/trimmomatic:0.39--hdfd78af_2"

[tool.hardware]
cpu_cores = 4
ram_gb = 4.0
disk_gb = 1.0

[tool.entrypoint]
command = "trimmomatic"
args_template = "PE -threads {cpu_cores} {reads_r1} {reads_r2} {out_r1} /dev/null {out_r2} /dev/null ILLUMINACLIP:/opt/conda/share/trimmomatic/adapters/TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36"

[tool.binaries]
exposed = [ "trimmomatic",]

[tool.factored]
spec_path = "specs/trimmomatic/0.39.0.yaml"
image_reference = "ghcr.io/tejasprabhune/bv-pkg/trimmomatic:0.39.0"
image_digest = "sha256:e7ab2840806cab12289b8ac3b792599509430478d8f2dd034f1ab42b2ab221aa"
