name = "seqkit"
version = "2.8.1"
channels = [
    "https://conda.anaconda.org/bioconda",
    "https://conda.anaconda.org/conda-forge",
]
packages = ["seqkit ==2.8.1"]
platform = "linux/amd64"

[entrypoint]
command = "/opt/conda/bin/seqkit"
