[tool]
id = "flye"
version = "2.9.4"
description = "De novo assembler for single-molecule sequencing reads (PacBio, Nanopore)"
homepage = "https://github.com/mikolmogorov/Flye"
license = "BSD-3-Clause"
tier = "core"
maintainers = [ "github:mikolmogorov",]
[[tool.inputs]]
name = "reads"
type = "fastq"
cardinality = "one"
description = "Long reads (Nanopore or PacBio)"

[[tool.outputs]]
name = "output_dir"
type = "dir"
cardinality = "one"
description = "Assembly output directory with assembly.fasta"

[tool.image]
backend = "docker"
reference = "quay.io/biocontainers/flye:2.9.4--py39hdf45acc_2"

[tool.hardware]
cpu_cores = 16
ram_gb = 32.0
disk_gb = 50.0

[tool.entrypoint]
command = "flye"
args_template = "--nano-raw {reads} --out-dir {output_dir} --threads {cpu_cores}"

[tool.binaries]
exposed = [ "flye",]

[tool.factored]
spec_path = "specs/flye/2.9.4.yaml"
image_reference = "ghcr.io/tejasprabhune/bv-pkg/flye:2.9.4"
image_digest = "sha256:97cd2c9acf728566f21e93e1564419ce34721320cf6c2364ed004120a4e1b702"
