name = "clustalo"
version = "1.2.4"
channels = [
    "https://conda.anaconda.org/bioconda",
    "https://conda.anaconda.org/conda-forge",
]
packages = ["clustalo ==1.2.4"]
platform = "linux/amd64"

[entrypoint]
command = "/opt/conda/bin/clustalo"
