name = "chopper"
version = "0.8.0"
channels = [
    "https://conda.anaconda.org/bioconda",
    "https://conda.anaconda.org/conda-forge",
]
packages = ["chopper ==0.8.0"]
platform = "linux/amd64"

[entrypoint]
command = "/opt/conda/bin/sh"
