[tool]
id = "interproscan"
version = "5.59.91"
description = "InterProScan: functional annotation of proteins by scanning member databases"
homepage = "https://www.ebi.ac.uk/interpro/search/sequence/"
license = "Apache-2.0"
tier = "community"
maintainers = [ "github:ebi-pf-team",]
[[tool.inputs]]
name = "proteins"
type = "fasta[protein]"
cardinality = "one"
description = "Input protein sequences"

[[tool.outputs]]
name = "output"
type = "file"
cardinality = "one"
description = "Functional annotations in TSV/GFF3/XML format"

[tool.image]
backend = "docker"
reference = "quay.io/biocontainers/interproscan:5.59_91.0--hec16e2b_1"

[tool.hardware]
cpu_cores = 8
ram_gb = 16.0
disk_gb = 30.0

[tool.entrypoint]
command = "interproscan.sh"
args_template = "--cpu {cpu_cores} -i {proteins} -o {output} -f TSV"

[tool.binaries]
exposed = [ "interproscan.sh",]

[tool.factored]
spec_path = "specs/interproscan/5.59.91.yaml"
image_reference = "ghcr.io/tejasprabhune/bv-pkg/interproscan:5.59.91"
image_digest = "sha256:aa1600dff82c2a4d78f61798c69818f19b01e7f7671e282c9f651b6ac6b82489"
